"""
tests/test_hdna_dp_equivalence.py — Phase 0/4 equivalence test suite.

Replays the golden fixtures from tests/fixtures/golden_hdna.json through
both the legacy code path (HSEEKER_FAST_HDNA unset / "0") and the new DP
code path (HSEEKER_FAST_HDNA=1) and asserts field-by-field equality.

The Phase 0 fixtures are generated by the CURRENT (unmodified) implementation
and are the oracle — do not edit expected values to make tests pass.

When Phase 4 lands, the DP path will be available and the parametrized
@pytest.mark.parametrize("use_dp", [False, True]) will exercise both code
paths.  Until then, only use_dp=False runs (Phase 0 validation).

Run:
    pytest tests/test_hdna_dp_equivalence.py -v
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path
from typing import Any

import pytest
import hseeker

FIXTURES_PATH = Path(__file__).parent / "fixtures" / "golden_hdna.json"

# ---------------------------------------------------------------------------
# Load fixtures at module import time so collection is fast.
# ---------------------------------------------------------------------------

def _load_fixtures() -> tuple[dict, dict]:
    if not FIXTURES_PATH.exists():
        return {}, {}
    with open(FIXTURES_PATH) as f:
        data = json.load(f)
    param_sets = data.pop("__param_sets__", {})
    return data, param_sets


_FIXTURES, _PARAM_SETS = _load_fixtures()

# True once Phase 4 integration is merged behind HSEEKER_FAST_HDNA
_DP_AVAILABLE = True


# ---------------------------------------------------------------------------
# Oracle: brute-force Python implementation of findHDNA_core's inner loop.
#
# This is the *independent* ground truth.  It must NOT be derived from or
# call the optimized code — it is a clean re-implementation of the spec
# from Section 1 of copilot_dp_optimization_instructions.md.
# ---------------------------------------------------------------------------

_BT = {}
for _b in "AGag":
    _BT[_b] = 1
for _b in "CTct":
    _BT[_b] = 2

def oracle_best_k(
    dna: str,
    ctr: int,
    sp: int,
    minrep: int,
    maxrep: int,
    purity_thresh: float,
    mismatch_tol: float,
) -> int:
    """Brute-force computation of best_k for a single (ctr, sp) pair.

    Exactly mirrors the C inner while-loop semantics from findHDNA_core:
      - Breaks immediately when right char has BT==0 (N / non-ACGT).
      - Left-side non-ACGT does NOT break the loop; it counts as a mismatch.
      - mismatch_budget is computed from maxrep (not running k).
      - Early-exit check is only inside k >= minrep block.
      - best_k = largest k in [minrep, K_final] where purity AND ratio valid.
    """
    total = len(dna)
    left_i  = ctr
    right_j = ctr + sp + 1
    k = 0
    mismatches = 0
    ga_count = 0
    ct_count = 0
    best_k = 0

    purity_thresh_int = int(purity_thresh * 100.0 + 0.5)
    mismatch_tol_int  = int(mismatch_tol  * 100.0 + 0.5)
    mismatch_budget   = int(mismatch_tol * maxrep)

    while left_i >= 0 and right_j < total and k < maxrep:
        lb = dna[left_i]
        bt_rb = _BT.get(dna[right_j], 0)

        if bt_rb == 0:
            break  # right-side non-ACGT: hard stop

        if lb != dna[right_j]:
            mismatches += 1
        k += 1

        if bt_rb == 1:
            ga_count += 1
        else:
            ct_count += 1

        if k >= minrep:
            ga_ok = ga_count * 100 >= purity_thresh_int * k
            ct_ok = ct_count * 100 >= purity_thresh_int * k
            ratio_ok = mismatches * 100 <= mismatch_tol_int * k
            if (ga_ok or ct_ok) and ratio_ok:
                best_k = k
            if mismatches > mismatch_budget:
                break

        left_i  -= 1
        right_j += 1

    return best_k


def oracle_scan(
    seq: str,
    minrep: int = 10,
    maxrep: int = 1000,
    maxspacer: int = 10,
    purity: float = 0.90,
    mismatch: float = 0.10,
) -> list[dict[str, Any]]:
    """Pure-Python oracle that replicates findHDNA_core output (no overlap removal).

    Returns a list of dicts with the same numeric fields as scan_sequence
    (start, end, arm_length, spacer_length, ga_pct, ct_pct, mirror_identity,
    is_perfect).  String fields (left_arm, spacer, right_arm, full_sequence)
    are also included for completeness.
    """
    dna = seq.lower()
    total = len(dna)
    hits = []

    purity_thresh_int = int(purity * 100.0 + 0.5)
    mismatch_tol_int  = int(mismatch * 100.0 + 0.5)

    for ctr in range(minrep - 1, total - minrep):
        if _BT.get(dna[ctr], 0) == 0:
            continue

        max_sp = min(maxspacer, total - minrep - ctr - 1)
        for sp in range(max_sp + 1):
            bk = oracle_best_k(dna, ctr, sp, minrep, maxrep, purity, mismatch)
            if bk < minrep:
                continue

            left_start  = ctr - bk + 1
            right_start = ctr + sp + 1

            # Recompute stats at best_k — left arm is accessed right-to-left
            # (dna[ctr], dna[ctr-1], ..., dna[left_start]) matched against
            # right arm left-to-right (dna[right_start], dna[right_start+1], ...)
            # t=0 → left=dna[ctr], right=dna[right_start]
            # t=1 → left=dna[ctr-1], right=dna[right_start+1], etc.
            mismatches = sum(
                1 for t in range(bk)
                if dna[ctr - t] != dna[right_start + t]
            )
            ga_count = sum(1 for t in range(bk) if _BT.get(dna[right_start + t], 0) == 1)
            ct_count = sum(1 for t in range(bk) if _BT.get(dna[right_start + t], 0) == 2)

            inv_k   = 1.0 / bk
            best_mir = 1.0 - mismatches * inv_k
            best_ga  = ga_count * inv_k
            best_ct  = ct_count * inv_k

            # is_perfect: uses exact float comparison (matches C float semantics
            # closely but Python floats are doubles — this may differ from C floats
            # for edge cases; the C code is the true oracle for is_perfect)
            is_perfect = ((best_ga == 1.0 or best_ct == 1.0) and best_mir == 1.0)

            spacer_str = dna[ctr + 1: ctr + sp + 1] if sp > 0 else "."
            left_arm   = dna[left_start: left_start + bk]
            right_arm  = dna[right_start: right_start + bk]
            full_seq   = left_arm + (spacer_str if sp > 0 else "") + right_arm

            hits.append({
                "start":           left_start + 1,
                "end":             right_start + bk,
                "arm_length":      bk,
                "spacer_length":   sp,
                "total_length":    bk * 2 + sp,
                "ga_pct":          best_ga * 100.0,
                "ct_pct":          best_ct * 100.0,
                "mirror_identity": best_mir * 100.0,
                "is_perfect":      is_perfect,
                "left_arm":        left_arm,
                "spacer":          spacer_str,
                "right_arm":       right_arm,
                "full_sequence":   full_seq,
            })
    return hits


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _float_close(a: float, b: float, tol: float = 1e-4) -> bool:
    return abs(a - b) <= tol


def _hit_key(h: dict) -> tuple:
    return (h["start"], h["end"], h["arm_length"], h["spacer_length"])


def _hits_equal(ref: list[dict], got: list[dict], label: str = "") -> None:
    """Assert two hit lists are field-by-field identical (order-independent)."""
    ref_keys = sorted(_hit_key(h) for h in ref)
    got_keys = sorted(_hit_key(h) for h in got)
    missing = set(ref_keys) - set(got_keys)
    extra   = set(got_keys) - set(ref_keys)
    assert not missing and not extra, (
        f"{label}: hit count mismatch ref={len(ref)} got={len(got)}\n"
        f"  missing from got: {list(missing)[:5]}\n"
        f"  extra in got:     {list(extra)[:5]}"
    )
    # Field-by-field check
    ref_map = {_hit_key(h): h for h in ref}
    got_map = {_hit_key(h): h for h in got}
    for key in ref_keys:
        r, g = ref_map[key], got_map[key]
        for field in ("arm_length", "spacer_length", "total_length",
                       "start", "end"):
            assert r[field] == g[field], (
                f"{label} key={key} field={field}: ref={r[field]} got={g[field]}"
            )
        for field in ("ga_pct", "ct_pct", "mirror_identity"):
            assert _float_close(r[field], g[field]), (
                f"{label} key={key} field={field}: ref={r[field]:.6f} got={g[field]:.6f}"
            )
        assert r["is_perfect"] == g["is_perfect"], (
            f"{label} key={key} is_perfect: ref={r['is_perfect']} got={g['is_perfect']}"
        )


# ---------------------------------------------------------------------------
# Phase 0: Verify current implementation matches golden fixtures.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not FIXTURES_PATH.exists(), reason="golden fixtures not generated yet")
@pytest.mark.parametrize("seq_name", [k for k in _FIXTURES if not k.startswith("__")])
def test_legacy_matches_golden(seq_name: str) -> None:
    """Current scan_sequence output must match the golden fixture exactly."""
    entry = _FIXTURES[seq_name]
    seq = entry["seq"]
    for param_key, expected_hits in entry["results"].items():
        params = _PARAM_SETS[param_key]
        got = hseeker.scan_sequence(seq, remove_overlaps=False, score=False, **params)
        _hits_equal(expected_hits, got,
                    label=f"{seq_name}/{param_key}")


# ---------------------------------------------------------------------------
# Phase 0: Oracle vs. current implementation — spot-check on key sequences.
#
# NOTE: is_perfect comparison between the Python oracle and C is best-effort
# because C uses 32-bit floats; we skip is_perfect in oracle comparisons but
# check all numeric fields.
# ---------------------------------------------------------------------------

ORACLE_SPOT_SEQS = {
    "GAMIR_SEQ":   ("GGGAAATTAAAGGG",  dict(minrep=6,  maxrep=50,   maxspacer=10, purity=0.80, mismatch=0.20)),
    "CTMIR_SEQ":   ("CCCTTTAATTTCCC",  dict(minrep=6,  maxrep=50,   maxspacer=10, purity=0.80, mismatch=0.20)),
    "PERFECT_SEQ": ("A" * 14,           dict(minrep=6,  maxrep=50,   maxspacer=10, purity=0.90, mismatch=0.10)),
    "PURE_GA":     ("GAGAGAGAGAGAGAGAGAGAGA", dict(minrep=6, maxrep=50, maxspacer=10, purity=0.80, mismatch=0.20)),
    "all_A_50":    ("A" * 50,           dict(minrep=6,  maxrep=50,   maxspacer=5,  purity=0.90, mismatch=0.10)),
    "N_flanked":   ("N"*20 + "GGGAAATTAAAGGG" + "N"*20, dict(minrep=6, maxrep=50, maxspacer=10, purity=0.80, mismatch=0.20)),
    "mismatch0":   ("GGGAAATTAAAGGG",  dict(minrep=6,  maxrep=50,   maxspacer=10, purity=1.0,  mismatch=0.0)),
    "N_right0":    ("AAAAAA" + "N" + "AAAAAA", dict(minrep=6, maxrep=50, maxspacer=5, purity=0.90, mismatch=0.10)),
}


@pytest.mark.parametrize("name,seq_params", list(ORACLE_SPOT_SEQS.items()))
def test_oracle_matches_c_implementation(name, seq_params):
    """Python oracle must produce the same hit keys as scan_sequence (no overlap removal)."""
    seq, params = seq_params
    c_hits = hseeker.scan_sequence(seq, remove_overlaps=False, score=False, **params)
    py_hits = oracle_scan(seq, **params)

    c_keys  = sorted(_hit_key(h) for h in c_hits)
    py_keys = sorted(_hit_key(h) for h in py_hits)
    missing = set(c_keys) - set(py_keys)
    extra   = set(py_keys) - set(c_keys)
    assert not missing and not extra, (
        f"[{name}] Oracle/C mismatch: C={len(c_hits)} Oracle={len(py_hits)}\n"
        f"  In C but not oracle: {list(missing)[:5]}\n"
        f"  In oracle but not C: {list(extra)[:5]}"
    )
    # Numeric field check
    c_map  = {_hit_key(h): h for h in c_hits}
    py_map = {_hit_key(h): h for h in py_hits}
    for key in c_keys:
        c, p = c_map[key], py_map[key]
        for field in ("ga_pct", "ct_pct", "mirror_identity"):
            assert _float_close(c[field], p[field], tol=0.5), (
                f"[{name}] key={key} {field}: C={c[field]:.4f} Oracle={p[field]:.4f}"
            )


# ---------------------------------------------------------------------------
# Phase 4 (future): DP path must also match golden fixtures.
# These tests are collected but skipped until _DP_AVAILABLE is flipped.
# ---------------------------------------------------------------------------

@pytest.mark.skipif(not _DP_AVAILABLE, reason="DP path not yet integrated (Phase 4)")
@pytest.mark.parametrize("seq_name", [k for k in _FIXTURES if not k.startswith("__")])
def test_dp_matches_golden(seq_name: str) -> None:
    """DP path (HSEEKER_FAST_HDNA=1) must produce identical output to golden fixtures."""
    entry = _FIXTURES[seq_name]
    seq = entry["seq"]
    old_val = os.environ.get("HSEEKER_FAST_HDNA")
    os.environ["HSEEKER_FAST_HDNA"] = "1"
    try:
        for param_key, expected_hits in entry["results"].items():
            params = _PARAM_SETS[param_key]
            got = hseeker.scan_sequence(seq, remove_overlaps=False, score=False, **params)
            _hits_equal(expected_hits, got,
                        label=f"DP/{seq_name}/{param_key}")
    finally:
        if old_val is None:
            os.environ.pop("HSEEKER_FAST_HDNA", None)
        else:
            os.environ["HSEEKER_FAST_HDNA"] = old_val


# ---------------------------------------------------------------------------
# Section 7 edge-case checklist (independent of fixture replay)
# ---------------------------------------------------------------------------

def test_ec_shorter_than_2minrep():
    """Sequence shorter than 2*minrep: no valid center exists."""
    assert hseeker.scan_sequence("AAAAAAAAAA", minrep=6, score=False) == []


def test_ec_all_n():
    """All-N sequence: no hits, no crash."""
    assert hseeker.scan_sequence("N" * 100, minrep=6, score=False) == []


def test_ec_single_n_at_right0():
    """N immediately at right0 — zero-length right arm, K_right_hard=0."""
    # center at pos 5, sp=0 → right0=6 = 'N' → hard stop immediately
    seq = "AAAAAANAAAAA"
    hits = hseeker.scan_sequence(seq, minrep=6, remove_overlaps=False, score=False)
    # No hit should have right_arm starting at position 7 (1-based index 6 in 0-based)
    for h in hits:
        assert h["right_arm"][0] != 'n', f"Hit starting at N: {h}"


def test_ec_n_left_only():
    """N on left side only — must NOT hard-stop; right arm still clean."""
    # If right arm alone would qualify, that's fine regardless of left-side N.
    # The C code only breaks on BT[right_char]==0, never on left char.
    seq = "NNNNNN" + "A" * 30
    # Run oracle to establish expected behavior
    params = dict(minrep=6, maxrep=50, maxspacer=5, purity=0.90, mismatch=0.10)
    c_hits = hseeker.scan_sequence(seq, remove_overlaps=False, score=False, **params)
    py_hits = oracle_scan(seq, **params)
    c_keys  = sorted(_hit_key(h) for h in c_hits)
    py_keys = sorted(_hit_key(h) for h in py_hits)
    assert c_keys == py_keys, (
        f"N-left-only mismatch: C={len(c_hits)} Oracle={len(py_hits)}"
    )


def test_ec_maxspacer_zero():
    """maxspacer=0: all returned hits must have spacer_length=0."""
    seq = "GAGAGAGAGAGAGAGAGAGA"
    for h in hseeker.scan_sequence(seq, minrep=6, maxspacer=0, score=False):
        assert h["spacer_length"] == 0


def test_ec_mismatch_zero_exact_mirror():
    """mismatch=0.0 — only exact-mirror hits allowed."""
    seq = "GGGAAATTAAAGGG"
    # arm=7 hit has 0 mismatches → should appear
    hits_strict = hseeker.scan_sequence(seq, minrep=6, purity=0.80, mismatch=0.0,
                                         remove_overlaps=False, score=False)
    assert any(h["mirror_identity"] == 100.0 for h in hits_strict)
    # All returned hits must have 100% mirror identity
    for h in hits_strict:
        assert h["mirror_identity"] == 100.0, f"Non-perfect hit under mismatch=0: {h}"


def test_ec_purity_one_mismatch_zero():
    """purity=1.0, mismatch=0.0 — strictest mode."""
    seq = "A" * 30  # pure-A: perfect mirror
    hits = hseeker.scan_sequence(seq, minrep=6, purity=1.0, mismatch=0.0,
                                  remove_overlaps=False, score=False)
    assert len(hits) > 0
    for h in hits:
        assert h["is_perfect"] is True


def test_ec_purity_zero():
    """purity=0.0 — always satisfied; must not divide by zero."""
    seq = "ACGTACGTACGTACGT"
    # Should not crash; may return hits or empty
    hits = hseeker.scan_sequence(seq, minrep=6, purity=0.0, mismatch=0.20,
                                  remove_overlaps=False, score=False)
    assert isinstance(hits, list)


def test_ec_arm_exactly_minrep():
    """Hit at exactly minrep arm length — off-by-one test."""
    # Construct a sequence where only arm=minrep is possible (surround with N)
    minrep = 6
    core = "A" * (minrep * 2)  # direct adjacency, arm=minrep exactly
    seq = "N" * 5 + core + "N" * 5
    hits = hseeker.scan_sequence(seq, minrep=minrep, maxrep=minrep,
                                  purity=0.90, mismatch=0.10,
                                  remove_overlaps=False, score=False)
    assert any(h["arm_length"] == minrep for h in hits), \
        f"Expected arm={minrep} hit, got: {hits}"


def test_ec_valid_k_non_monotone():
    """valid(k) can be false then true at a larger k; best_k picks the larger."""
    # Build a sequence where:
    # - at k=minrep: ratio_ok fails (too many early mismatches)  
    # - at k=minrep+2: a run of GA restores purity and ratio passes
    # Use: right arm = "AAAC" + "AAAA"  (C at position 4 causes mismatch)
    #      left arm mirrors this
    # With purity=0.80 and mismatch=0.25:
    # k=6: ga=5, mis=1 → ga_pct=83%, ratio=16% → VALID (best_k=6)
    # k=7: add 'a': ga=6, mis=1 → ga_pct=86%, ratio=14% → VALID (best_k=7)
    seq = "AAACAAAA" + "AAACAAAA"  # direct mirror
    hits = hseeker.scan_sequence(seq, minrep=6, maxrep=50,
                                  purity=0.75, mismatch=0.20,
                                  remove_overlaps=False, score=False)
    if hits:
        best_hit = max(hits, key=lambda h: h["arm_length"])
        oracle_hits = oracle_scan(seq, minrep=6, maxrep=50,
                                   purity=0.75, mismatch=0.20)
        oracle_best = max(oracle_hits, key=lambda h: h["arm_length"]) if oracle_hits else None
        if oracle_best:
            assert best_hit["arm_length"] == oracle_best["arm_length"]


def test_ec_lowercase_uppercase_mixed():
    """All three case variants must give identical results."""
    seq = "GGGaaaTTAAAGGG"
    upper = hseeker.scan_sequence(seq.upper(), minrep=6, score=False)
    lower = hseeker.scan_sequence(seq.lower(), minrep=6, score=False)
    mixed = hseeker.scan_sequence(seq, minrep=6, score=False)
    assert len(upper) == len(lower) == len(mixed)


def test_ec_iupac_non_N_ambiguity():
    """IUPAC codes R, Y, W, S must be treated same as N (BT==0 → hard stop)."""
    # R at right0 → zero arm extension just like N
    seq_n = "AAAAAA" + "N" + "AAAAAA"
    seq_r = "AAAAAA" + "R" + "AAAAAA"
    hits_n = hseeker.scan_sequence(seq_n, minrep=6, remove_overlaps=False, score=False)
    hits_r = hseeker.scan_sequence(seq_r, minrep=6, remove_overlaps=False, score=False)
    c_keys_n = sorted(_hit_key(h) for h in hits_n)
    c_keys_r = sorted(_hit_key(h) for h in hits_r)
    assert c_keys_n == c_keys_r, \
        f"N and R should produce same hits but N={len(hits_n)} R={len(hits_r)}"


def test_ec_run_ends_at_k_total_zero_mismatches():
    """Run ending exactly at K_total with 0 mismatches — last-run, no trailing mismatch."""
    seq = "A" * 60  # pure A, no N: K_total limited only by maxrep
    maxrep = 20
    hits = hseeker.scan_sequence(seq, minrep=6, maxrep=maxrep,
                                  purity=0.90, mismatch=0.10,
                                  remove_overlaps=False, score=False)
    # Every hit must have arm_length <= maxrep
    for h in hits:
        assert h["arm_length"] <= maxrep
    # Some hits should have arm_length == maxrep (reaching the ceiling)
    assert any(h["arm_length"] == maxrep for h in hits), \
        f"Expected hits at maxrep={maxrep}, got max_arm={max((h['arm_length'] for h in hits), default=0)}"


def test_ec_two_ctrs_same_right0_purity_not_leaked():
    """Two (ctr,sp) pairs sharing the same right0 must not leak mismatch context."""
    # right0 = ctr + sp + 1; (ctr=5,sp=0) and (ctr=6,sp=-1) share right0=6 — but
    # the actual loop uses sp>=0, so (ctr=4,sp=2) and (ctr=5,sp=1) share right0=7.
    seq = "A" * 30
    params = dict(minrep=6, maxrep=20, maxspacer=5, purity=0.90, mismatch=0.10)
    hits = hseeker.scan_sequence(seq, remove_overlaps=False, score=False, **params)
    oracle_hits = oracle_scan(seq, **params)
    _hits_equal(hits, oracle_hits, label="shared-right0-context-leak")
